### ISSUE TITLE
Should set VELOREN_USERDATA (or similar)

### ISSUE THREAD

**Issue by stefanor** [timsueberkrueb/veloren-snap#1]
```
$ snap run veloren
thread 'main' panicked at 'Recompile with VELOREN_USERDATA_STRATEGY set to "system" or "executable" to run the binary outside of the project folder', common/src/util/userdata_dir.rs:55:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Either it should be recompiled with a defined strategy or, probably, set something like `VELOREN_USERDATA=$SNAP_USER_DATA` in the wrapper.

See: https://github.com/veloren/veloren/blob/2c09db613b479ce0cd1bceab5e016763a5b31a8e/common/src/util/userdata_dir.rs#L14-L19

**Comment by timsueberkrueb** [comment]
Hey @stefanor, thanks for reporting. I'm aware of the problem, in fact, I have already fixed this locally, but unfortunately, there is another breakage which requires changes in the Veloren code (or doing some ugly patching in the snap which I'd prefer to avoid).

---

**Detailed explanation of the additional breakage:**

Veloren persists the log path in `settings.ron`.
Snap packages are confined and store their user data in `~/snap/<snap-name>/<snap-revision>`.
The following scenario leads to breakage: 
User installs `veloren`, snap revision `3`
Veloren now persists the log path location (.e.g. `~/snap/veloren/3/logs`) which was originally obtained from XDG env vars in its `settings.ron` file.
The snap gets updated to revision `4`. The directory `~/snap/veloren/3` gets copied to `~/snap/veloren/4`, `~/snap/veloren/3` is removed (usually the last revision will be kept as backup but it will be removed eventually).
Veloren segfaults on launch as it gets an apparmor denial trying to access `~/snap/veloren/3/logs`.

Usually there is a `~/snap/<snap-name>/current` symlink to the latest revision but Veloren seems to resolve that (even when setting `VOXYGEN_LOGS`), therefore leading to the breakage.

**Comment by timsueberkrueb** [comment]
Should be fixed once [this merge request](https://gitlab.com/veloren/veloren/-/merge_requests/1565) or an equivalent fix is merged.

**Comment by timsueberkrueb** [comment]
Should be fixed now
