### ISSUE TITLE
the game wont load on my computer

### ISSUE THREAD

**Issue by redduck79** [timsueberkrueb/veloren-snap#6]
downloaded game a couple days ago and it wont load. 
i am using linux ubuntu on my computer.

**Comment by moreavy** [comment]
How did you install it? (snap, apt, download)

**Comment by timsueberkrueb** [comment]
Hey @redduck79, thanks for reporting a bug.

Please **provide the following details** about your problem:
* Log that you get when running Veloren from the terminal (please use [paste.ubuntu.com](https://paste.ubuntu.com/) or a similar service and post the link)
* Operating system and version
* Graphics card and graphics driver (`sudo lshw -C video`)
* Are you using Wayland or X11 ([how to find out](https://askubuntu.com/a/990224))?

Please **make sure your system supports Vulkan** and that you have [Vulkan installed on your system](https://linuxconfig.org/install-and-test-vulkan-on-linux) (there's also [a guide on the Arch Linux wiki](https://wiki.archlinux.org/title/Vulkan#Installation)). Unfortunately, Veloren dropped OpenGL support and requires Vulkan now.

Please also install `vulkan-tools` (e.g. `apt install vulkan-tools` on Ubuntu) and run:

```
vulkaninfo
```

and **submit the output** (it's pretty long, so please use [paste.ubuntu.com](https://paste.ubuntu.com/), [paste.gg](https://paste.gg), or a similar service and post the link).

Next, we have to **test whether this is a snap-specific** issue or a Veloren specific issue.
The easiest way to do so is for you to [download Veloren](https://veloren.net/download/) using a method other than snap (e.g. using [this tarball](https://github.com/veloren/airshipper/releases/latest/download/airshipper-linux.tar.gz)) and test if that works.

Thanks for your help in debugging this issue!

**Comment by redduck79** [comment]
I downloaded the game from the App Store in Ubuntu. The game does nothing when I click on it. 
I will look into those things you suggested after work. Thanks for the Info. 
There is probably nothing wrong with the game I just don’t know what I am doing. I am pretty new to the linux operating system.

**Comment by timsueberkrueb** [comment]
No problem, the first thing would be to open a terminal (e.g. press `Ctrl+Alt+T`) and enter the commands:
`which veloren`
and
`veloren`.

The first command would say `/snap/bin/veloren` if the Veloren version you have installed is a snap package. The second command should launch the game or provide error messages that can help us debug the problem.

Thanks!

**Comment by redduck79** [comment]
Ok I clicked on the paste.Ubuntu link opened a account and pasted some of the things you asked for. I am not sure I did it correctly so here is what it said after I hit submit. Paste from David Doebele 16 September 2021 0:54 +0000. 

I downloaded the snap version and I am using wayland. 

I also tried to download the game from the tarball link you put in the reply and I got this when I tried to open it. Again I am fairly new with linux. 
This message popped up: could not open “air shipper-linux. tar-2” Archive not supported. 

I hope I at least got you something you can work with. Please let me know if I forgot something or completely didn’t even get you anything at all. 

Thanks again for your help can’t wait to get started on this game.

**Comment by moreavy** [comment]
@redduck79 Install veloren using Ubuntu Software (Snap Store) in Ubuntu on Xorg (x11).

**Comment by redduck79** [comment]
Ok not sure how to go about doing that. But I will look into it. Thanks.

**Comment by timsueberkrueb** [comment]
> Ok I clicked on the paste.Ubuntu link opened a account and pasted some of the things you asked for. I am not sure I did it correctly so here is what it said after I hit submit

You would have to give me the url e.g. `paste.ubuntu.com/<some number>` after you submitted it in order for me to be able to see your paste.

As @redduck79 said, try if it works on Xorg rather than Wayland ([how to switch](https://itsfoss.com/switch-xorg-wayland/)).

Thanks!

**Comment by redduck79** [comment]
I switched over to x11 and it’s still not loading. When I try to start the game from the command line a screen pops up for a split second and goes away.  And here is the url you asked for I hope this what you are needing. 
https://paste.ubuntu.com/p/XXbpT9YMKm. 
I tried to include everything you asked for from yesterday. I am running the latest version of Ubuntu as well.

**Comment by timsueberkrueb** [comment]
Hey @redduck79 thanks for the information!

Unfortunately, it seems like your Graphics card (Intel 2nd gen integrated graphics) is [not supported by Vulkan](https://askubuntu.com/a/1096989). Though the Veloren developers have told me that OpenGL support is probably going to come back within a month or two, depending on how the support in `wgpu`, the graphics library they use, matures.

However, you could try to run the last stable release that supported OpenGL, `v0.9.0`: https://veloren.net/download-other

Additionally, if you happen to dual-boot with Windows, you should be able to run Veloren there.

Sorry for the inconvenience.

**Comment by redduck79** [comment]
Cool thanks for the info. I will try and figure something out. I have a newer computer I may try to dual boot. I am wanting to get away from windows anyhow. 
Thanks for all the help have a good weekend.
